services:
  postgres:
    image: postgres:latest
    container_name: PostgresDB_container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root_secret
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgresdb:/var/lib/postgresql/data
    networks:
      - appNetwork

  # Visor base de datos
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - appNetwork
  
  # nextjs:
  #   build:
  #     context: ./next
  #     dockerfile: Dockerfile
  #   container_name: gvmart_nextjs_container
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     DATABASE_URL: "postgresql://root:root_secret@postgres:5432/mydatabase"
  #   volumes:
  #     - ./next:/app
  #     - /app/node_modules
  #   command: ["npm", "run", "dev"]
  #   depends_on:
  #     - postgres
  #   networks:
  #     - appNetwork

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    volumes:
      - redis_data:/data
    networks:
      - appNetwork

volumes:
  postgresdb:
  redis_data:

networks:
  appNetwork:
    driver: bridge
